// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo2

// Injectors from wire.go:

func InitMission(p PlayerParam, m MonsterParam) Mission {
	player := NewPlayer(p)
	monster := NewMonster(m)
	mission := NewMission(player, monster)
	return mission
}
