// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo5

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(p PlayerParam) EndingA {
	player := NewPlayer(p)
	monster := _wireMonsterValue
	endingA := EndingA{
		Player:  player,
		Monster: monster,
	}
	return endingA
}

var (
	_wireMonsterValue = kitty
)

func InitEndingB(p PlayerParam) EndingB {
	player := NewPlayer(p)
	monster := _wireMonsterValue
	endingB := EndingB{
		Player:  player,
		Monster: monster,
	}
	return endingB
}

// wire.go:

// 有些类型是单例，例如配置，数据库对象（sql.DB）
// 可以使用 wire.Value 绑定值，使用wire.InterfaceValue绑定接口
// 怪兽一直是一个Kitty
var kitty = Monster{"Kitty"}

var monsterPlayerSet = wire.NewSet(wire.Value(kitty), NewPlayer)

var endingASet = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingA), "*"))

var endingBSet = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingB), "*"))
