// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package base

import (
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initializeBaz(ctx context.Context) (Baz, error) {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	baz, err := ProvideBaz(ctx, bar)
	if err != nil {
		return Baz{}, err
	}
	return baz, nil
}

// wire.go:

// Any non-injector declarations found in a file with injectors will be copied into the generated file.
var SuperSet = wire.NewSet(ProvideFoo, ProvideBar, ProvideBaz)
