// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo

// Injectors from wire.go:

// docs: https://zhuanlan.zhihu.com/p/110453784
func InitMission(name string) Mission {
	player := NewPlayer(name)
	monster := NewMonster(name)
	mission := NewMission(player, monster)
	return mission
}
