// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo3

// Injectors from wire.go:

func InitMission(p PlayerParam, m MonsterParam) (Mission, error) {
	player, err := NewPlayer(p)
	if err != nil {
		return Mission{}, err
	}
	monster := NewMonster(m)
	mission := NewMission(player, monster)
	return mission, nil
}
