// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tutorial

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeEvent() Event {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}

func InitializeEvent2(phrase string) (Event2, error) {
	message := NewMessage2(phrase)
	greeter2 := NewGreeter2(message)
	event2, err := NewEvent2(greeter2)
	if err != nil {
		return Event2{}, err
	}
	return event2, nil
}

func InitializeEvent2WithSet(phrase string) (Event2, error) {
	message := NewMessage2(phrase)
	greeter2 := NewGreeter2(message)
	event2, err := NewEvent2(greeter2)
	if err != nil {
		return Event2{}, err
	}
	return event2, nil
}

// wire.go:

var Event2Set = wire.NewSet(NewGreeter2, NewMessage2)
