// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package fields

// Injectors from wire.go:

func InjectMessage() string {
	foo := provideFoo()
	string2 := Gets(foo)
	return string2
}

// You can instead use wire.FieldsOf to use those fields directly without writing getS:
func InjectMessage2() string {
	foo := provideFoo()
	string2 := foo.S
	return string2
}
