// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package demo4

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(p PlayerParam, m MonsterParam) EndingA {
	player := NewPlayer(p)
	monster := NewMonster(m)
	endingA := EndingA{
		Player:  player,
		Monster: monster,
	}
	return endingA
}

func InitEndingB(p PlayerParam, m MonsterParam) EndingB {
	player := NewPlayer(p)
	monster := NewMonster(m)
	endingB := EndingB{
		Player:  player,
		Monster: monster,
	}
	return endingB
}

// wire.go:

var monsterPlayerSet = wire.NewSet(NewMonster, NewPlayer)

var endingASet = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingA), "*"))

var endingBSet = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingB), "*"))
